### ISSUE TITLE
👍 

### ISSUE THREAD

**Issue by marcferna** [Jane3/Thanx_assignment#1]
Hi Jane,

Thank you so much for submitting this assignment. Overall looks good. Some improvements that could be done:
- Use the build settings that are mentioned in the "hints" section of the instructions:
`gym(scheme: "YourScheme", configuration: "Debug", skip_codesigning: true, skip_archive: true)`

(even with that, I'm still encountering some build issues that I would need to dig more to see what is going on)

- The travis configuration then should use that "lane" and build the app:
```
jobs:
  include:
    - stage: build-ios
      language: node_js
      node_js: 14.15.5
      os: osx
      osx_image: xcode12.2
      before_install:
        - gem install bundler
        - bundle install
      install: yarn
      before_script:
        - cd ios && bundle exec pod install && cd ..
      script: bundle exec fastlane ios gymAppAdHoc
```

No need to apply these changes. Overall looks good.
